spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://j8a405.p.ssafy.io:3306/swing?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: swing
    password: asdf1234
  jpa:
    database: mysql
    properties:
      hibernate:
        use_sql_comments : true
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 557054166791-rr3e9e38dt8cejv8ls34lci2aeasatah.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          kakao:
            client-id: 45a213cf4d624eaba8320eff3e3bf290
            client-secret: Hat4rblqoUfLZXChstKh5n7K1rxR9DVk
            scope:
              - profile_nickname
            client-name: Kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST #카카오는 필수 파라미터를 POST로 요청해야됌!
            redirect-uri: http://localhost:8080/api/login/oauth2/code/kakao #코드를 받는 uri(naver 의 콜백 uri)

        provider: #네이버의 provider는 등록되어 있지 않아 사용자가 등록해야된다.
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: kakao_account
# jwt secret key
jwt:
  secret: thisisthesecretkeyfortheswingproject



file:
  path: C:/images
cloud:
  aws:
    credentials:
      access-key: AKIAZ4LSOWIH3XXT3WSI
      secret-key: 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
    s3:
      bucket : a405-swing
    region:
      static: ap-northeast-2
    stack:
      auto: false

